name: Deploy on push to master

on:
  push:
    branches: [ master ]

jobs:

  build:
    
    runs-on: ubuntu-latest

    steps:
    - name: Update the live server web image
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: root
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}  
        # Connect to server, navigate to project, pull from github and rebuild image
        script: |
          cd /home/user/Nginx-Proxy/ImBrad
          echo 'Server pulling latest changes from Git Repo...'
          git pull origin master
          cd ..
          echo 'Rebuilding docker image...'
          docker-compose up --detach --build

