name: Deploy on push to master

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout Repositry'
      uses: actions/checkout@v2
    - name: Build docker image
      uses: docker/build-push-action@v1
      with: 
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: rocstack/imbrad
        tags: latest

    # - name: Update the live server web image
    #   uses: appleboy/ssh-action@master
    #   with:
    #     host: ${{ secrets.SSH_HOST }}
    #     username: root
    #     key: ${{ secrets.SSH_KEY }}
    #     passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}  
    #     # Connect to server, navigate to project, pull from github and rebuild image
    #     script: |
    #       cd /home/user/Nginx-Proxy
    #       echo 'Rebuilding docker image...'
    #       docker-compose up --detach --build
